import os
import json
import base64
import io
from typing import Optional
import google.generativeai as genai


def generate_infographic(title: str, data: list, key_highlight: str) -> Optional[str]:
    """
    Uses Gemini image generation to create a business infographic.

    Args:
        title: Chart/analysis title
        data: List of dicts (from df.to_dict(orient="records"))
        key_highlight: A single key insight string derived from the data

    Returns:
        Base-64 encoded PNG image string, or None on failure.
    """
    api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
    if not api_key:
        return None

    try:
        # Truncate data payload to stay within prompt limits
        data_str = json.dumps(data[:20], indent=2)
        if len(data_str) > 3000:
            data_str = data_str[:3000] + "\n... [truncated]"

        prompt = f"""Create a clean, professional business infographic for the following analytics data.

Title: {title}

Data:
{data_str}

Key Highlight: {key_highlight}

Design Requirements:
- Style: Corporate / Executive
- Color theme: Blue and white (#003087, #1e6dc9, #ffffff)
- Include a bold title at the top
- Render the data as a clear bar chart or table
- Display the Key Highlight as a prominent callout box
- Include a small footer: "Generated by DataTalk AI"
- Layout: Clean, minimal, well-spaced
- Font: Sans-serif, professional
- Background: White or very light grey
"""

        genai.configure(api_key=api_key)

        # Use gemini-2.0-flash-exp which supports image generation
        model = genai.GenerativeModel("gemini-2.0-flash-exp")
        response = model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(
                response_mime_type="image/png"
            ),
        )

        # Extract image bytes from response
        for part in response.candidates[0].content.parts:
            if hasattr(part, "inline_data") and part.inline_data:
                return base64.b64encode(part.inline_data.data).decode("utf-8")

        return None

    except Exception:
        return None


def derive_key_highlight(df_records: list, title: str) -> str:
    """
    Deterministically derive a key highlight sentence from the top result.
    No LLM involved — pure Python logic.
    """
    if not df_records:
        return "No data available for highlight."

    # Try to find numeric column for the highlight
    first = df_records[0]
    numeric_keys = [k for k, v in first.items() if isinstance(v, (int, float))]
    cat_keys = [k for k, v in first.items() if isinstance(v, str)]

    if not numeric_keys:
        return f"{title}: {len(df_records)} records returned."

    metric_key = numeric_keys[0]
    cat_key = cat_keys[0] if cat_keys else None

    # Find max value record
    try:
        top_record = max(df_records, key=lambda r: r.get(metric_key, 0))
        top_val = top_record[metric_key]
        top_label = top_record.get(cat_key, "") if cat_key else ""

        if isinstance(top_val, float):
            top_val_str = f"{top_val:.2f}"
        else:
            top_val_str = str(top_val)

        if top_label:
            return f"{top_label} leads with a {metric_key} of {top_val_str}."
        else:
            return f"Peak {metric_key} observed: {top_val_str}."
    except Exception:
        return f"{title}: data analysis complete."
